#Create a patients
POST http://localhost:4004/api/patients
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Rahul Sharma Test",
  "email": "rahul.sharm242494925@example.in",
  "address": "12 MG Road, Delhi",
  "dateOfBirth": "1985-06-15",
  "registeredDate": "2024-01-10"
}